mod_name = "GayCatTweaks - Fabric Edition"
mod_id = "gaycat_tweaks"
mod_group = "org.teamvoided"
mod_version = "1.0.0"
mod_description = "QoL Tweaks for GayCatSMP"
github_repo = "Teamvoided/GayCatTweaks"
discord_invite = "https://discord.gg/KZ5Q364hEg"
authors = [ "TheEnderCore" ]
license = "MIT"
version_range = ">=1.21.1 <1.21.2"
